[build-system]
requires = [
    "scikit_build_core>=1",
]
build-backend = "scikit_build_core.build"

[project]
name = "praat-parselmouth"
# version = <see setup.py>
description = "Praat in Python, the Pythonic way"
license = "GPL-3.0-or-later"
license-files = [
    "LICENSE",
    "praat/main/GNU_General_Public_License.txt",
    "praat/main/gpl-3.0.txt",
    "pybind11/LICENSE",
    "extern/fmt/LICENSE"
]
authors = [
    { name = "Yannick Jadoul", email = "yannick.jadoul@gmail.com" },
]
readme = "res/README_PyPI.md"
requires-python = ">=3.9"
keywords = ["praat", "speech", "signal processing", "phonetics"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Unix",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = [
    "numpy>=1.7.0"
]
dynamic = ["version"]

[project.urls]
"Homepage" = "https://github.com/YannickJadoul/Parselmouth"
"Bug Tracker" = "https://github.com/YannickJadoul/Parselmouth/issues"
"Documentation" = "https://parselmouth.readthedocs.io/"
"Source Code" = "https://github.com/YannickJadoul/Parselmouth"

[tool.scikit-build]
minimum-version = "build-system.requires"
cmake.version = "CMakeLists.txt"
sdist.inclusion-mode = "explicit"
sdist.include = [
    "/*.md",
    "/CITATION.cff",
    "/LICENSE",
    "/pyproject.toml",
    "/CMakeLists.txt",
    "/requirements.txt",
    "/docs/",
    "/extern/",
    "/praat/",
    "/pybind11/",
    "/res/",
    "/src/",
    "/tests/"
]
sdist.exclude = [
    "*.py[co]",
    ".git",
    ".gitattributes",
    ".github",
    ".gitignore",
    "/docs/_build",
    "/praat/generate/Unicode/*.pdf"
]
sdist.reproducible = false
wheel.packages = []

[[tool.dynamic-metadata]]
provider = "scikit_build_core.metadata.regex"
field = "version"
input = "src/version.h"
regex = "^#define PARSELMOUTH_VERSION (?P<value>[0-9a-z.]+)$"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests"
]

[tool.check-manifest]
ignore = [
    ".clang-format",
    ".github/**",
    ".gitmodules",
    ".pre-commit-config.yaml",
    ".readthedocs.yml",
    "binder",
    "binder/*",
    "praat/generate/Unicode/*.pdf"
]
